/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * Owner: mark@famo.us
 * @license MPL 2.0
 * @copyright Famous Industries, Inc. 2014
 */

define(["require","exports","module","famous/core/Modifier","famous/core/Transform","famous/transitions/Transitionable","famous/transitions/TransitionableTransform"],function(t,i,s){function n(t){this._transformState=new a(r.identity),this._opacityState=new o(1),this._originState=new o([0,0]),this._alignState=new o([0,0]),this._sizeState=new o([0,0]),this._modifier=new e({transform:this._transformState,opacity:this._opacityState,origin:null,align:null,size:null}),this._hasOrigin=!1,this._hasAlign=!1,this._hasSize=!1,t&&(t.transform&&this.setTransform(t.transform),void 0!==t.opacity&&this.setOpacity(t.opacity),t.origin&&this.setOrigin(t.origin),t.align&&this.setAlign(t.align),t.size&&this.setSize(t.size))}var e=t("famous/core/Modifier"),r=t("famous/core/Transform"),o=t("famous/transitions/Transitionable"),a=t("famous/transitions/TransitionableTransform");n.prototype.setTransform=function(t,i,s){return this._transformState.set(t,i,s),this},n.prototype.setOpacity=function(t,i,s){return this._opacityState.set(t,i,s),this},n.prototype.setOrigin=function(t,i,s){return null===t?(this._hasOrigin&&(this._modifier.originFrom(null),this._hasOrigin=!1),this):(this._hasOrigin||(this._hasOrigin=!0,this._modifier.originFrom(this._originState)),this._originState.set(t,i,s),this)},n.prototype.setAlign=function(t,i,s){return null===t?(this._hasAlign&&(this._modifier.alignFrom(null),this._hasAlign=!1),this):(this._hasAlign||(this._hasAlign=!0,this._modifier.alignFrom(this._alignState)),this._alignState.set(t,i,s),this)},n.prototype.setSize=function(t,i,s){return null===t?(this._hasSize&&(this._modifier.sizeFrom(null),this._hasSize=!1),this):(this._hasSize||(this._hasSize=!0,this._modifier.sizeFrom(this._sizeState)),this._sizeState.set(t,i,s),this)},n.prototype.halt=function(){this._transformState.halt(),this._opacityState.halt(),this._originState.halt(),this._alignState.halt(),this._sizeState.halt()},n.prototype.getTransform=function(){return this._transformState.get()},n.prototype.getFinalTransform=function(){return this._transformState.getFinal()},n.prototype.getOpacity=function(){return this._opacityState.get()},n.prototype.getOrigin=function(){return this._hasOrigin?this._originState.get():null},n.prototype.getAlign=function(){return this._hasAlign?this._alignState.get():null},n.prototype.getSize=function(){return this._hasSize?this._sizeState.get():null},n.prototype.modify=function(t){return this._modifier.modify(t)},s.exports=n});