/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * Owner: david@famo.us
 * @license MPL 2.0
 * @copyright Famous Industries, Inc. 2014
 */

define(["require","exports","module","famous/physics/PhysicsEngine","famous/physics/bodies/Particle","famous/physics/constraints/Snap","famous/math/Vector"],function(t,i,s){function e(t){t=t||0,this.endState=new v(t),this.initState=new v,this._dimensions=1,this._restTolerance=1e-10,this._absRestTolerance=this._restTolerance,this._callback=void 0,this.PE=new g,this.particle=new m,this.spring=new _({anchor:this.endState}),this.PE.addBody(this.particle),this.PE.attach(this.spring,this.particle)}function n(){return this.particle.getEnergy()+this.spring.getEnergy(this.particle)}function o(){var t=this.endState.sub(this.initState).normSquared();this._absRestTolerance=0===t?this._restTolerance:this._restTolerance*t}function a(t){this.endState.set(t),o.call(this)}function c(){this.PE.wake()}function h(){this.PE.sleep()}function l(t){this.particle.position.set(t)}function r(t){this.particle.velocity.set(t)}function p(){return 0===this._dimensions?this.particle.getPosition1D():this.particle.getPosition()}function u(){return 0===this._dimensions?this.particle.getVelocity1D():this.particle.getVelocity()}function d(t){this._callback=t}function f(t){var i=e.DEFAULT_OPTIONS;void 0===t.period&&(t.period=i.period),void 0===t.dampingRatio&&(t.dampingRatio=i.dampingRatio),void 0===t.velocity&&(t.velocity=i.velocity),this.spring.setOptions({period:t.period,dampingRatio:t.dampingRatio}),r.call(this,t.velocity)}function y(){if(this.PE.isSleeping()){if(this._callback){var t=this._callback;this._callback=void 0,t()}}else n.call(this)<this._absRestTolerance&&(l.call(this,this.endState),r.call(this,[0,0,0]),h.call(this))}var g=t("famous/physics/PhysicsEngine"),m=t("famous/physics/bodies/Particle"),_=t("famous/physics/constraints/Snap"),v=t("famous/math/Vector");e.SUPPORTS_MULTIPLE=3,e.DEFAULT_OPTIONS={period:100,dampingRatio:.2,velocity:0},e.prototype.reset=function(t,i){this._dimensions=t instanceof Array?t.length:0,this.initState.set(t),l.call(this,t),a.call(this,t),i&&r.call(this,i),d.call(this,void 0)},e.prototype.getVelocity=function(){return u.call(this)},e.prototype.setVelocity=function(t){this.call(this,r(t))},e.prototype.isActive=function(){return!this.PE.isSleeping()},e.prototype.halt=function(){this.set(this.get())},e.prototype.get=function(){return y.call(this),p.call(this)},e.prototype.set=function(t,i,s){if(!i)return this.reset(t),void(s&&s());this._dimensions=t instanceof Array?t.length:0,c.call(this),f.call(this,i),a.call(this,t),d.call(this,s)},s.exports=e});