/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * Owner: david@famo.us
 * @license MPL 2.0
 * @copyright Famous Industries, Inc. 2014
 */

define(["require","exports","module","famous/physics/PhysicsEngine","famous/physics/bodies/Particle","famous/physics/forces/Spring","famous/math/Vector"],function(t,i,s){function e(t){t=t||0,this.endState=new P(t),this.initState=new P,this._dimensions=void 0,this._restTolerance=1e-10,this._absRestTolerance=this._restTolerance,this._callback=void 0,this.PE=new y,this.spring=new _({anchor:this.endState}),this.particle=new m,this.PE.addBody(this.particle),this.PE.attach(this.spring,this.particle)}function n(){return this.particle.getEnergy()+this.spring.getEnergy(this.particle)}function o(t){this.particle.setPosition(t)}function a(t){this.particle.setVelocity(t)}function c(){return 0===this._dimensions?this.particle.getPosition1D():this.particle.getPosition()}function r(){return 0===this._dimensions?this.particle.getVelocity1D():this.particle.getVelocity()}function h(t){this._callback=t}function l(){this.PE.wake()}function p(){this.PE.sleep()}function d(){if(this.PE.isSleeping()){if(this._callback){var t=this._callback;this._callback=void 0,t()}}else n.call(this)<this._absRestTolerance&&(o.call(this,this.endState),a.call(this,[0,0,0]),p.call(this))}function f(t){var i=e.DEFAULT_OPTIONS;void 0===t.period&&(t.period=i.period),void 0===t.dampingRatio&&(t.dampingRatio=i.dampingRatio),void 0===t.velocity&&(t.velocity=i.velocity),t.period<150&&(t.period=150,console.warn("The period of a SpringTransition is capped at 150 ms. Use a SnapTransition for faster transitions")),this.spring.setOptions({period:t.period,dampingRatio:t.dampingRatio}),a.call(this,t.velocity)}function u(){var t=this.endState.sub(this.initState).normSquared();this._absRestTolerance=0===t?this._restTolerance:this._restTolerance*t}function g(t){this.endState.set(t),u.call(this)}var y=t("famous/physics/PhysicsEngine"),m=t("famous/physics/bodies/Particle"),_=t("famous/physics/forces/Spring"),P=t("famous/math/Vector");e.SUPPORTS_MULTIPLE=3,e.DEFAULT_OPTIONS={period:300,dampingRatio:.5,velocity:0},e.prototype.reset=function(t,i){this._dimensions=t instanceof Array?t.length:0,this.initState.set(t),o.call(this,t),g.call(this,t),i&&a.call(this,i),h.call(this,void 0)},e.prototype.getVelocity=function(){return r.call(this)},e.prototype.setVelocity=function(t){this.call(this,a(t))},e.prototype.isActive=function(){return!this.PE.isSleeping()},e.prototype.halt=function(){this.set(this.get())},e.prototype.get=function(){return d.call(this),c.call(this)},e.prototype.set=function(t,i,s){if(!i)return this.reset(t),void(s&&s());this._dimensions=t instanceof Array?t.length:0,l.call(this),f.call(this,i),g.call(this,t),h.call(this,s)},s.exports=e});