/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * Owner: david@famo.us
 * @license MPL 2.0
 * @copyright Famous Industries, Inc. 2014
 */

define(["require","exports","module","./Transitionable","famous/core/Transform","famous/utilities/Utility"],function(t,s,e){function i(t){this._final=l.identity.slice(),this.translate=new n([0,0,0]),this.rotate=new n([0,0,0]),this.skew=new n([0,0,0]),this.scale=new n([1,1,1]),t&&this.set(t)}function a(){return l.build({translate:this.translate.get(),rotate:this.rotate.get(),skew:this.skew.get(),scale:this.scale.get()})}var n=t("./Transitionable"),l=t("famous/core/Transform"),r=t("famous/utilities/Utility");i.prototype.setTranslate=function(t,s,e){return this.translate.set(t,s,e),this._final=this._final.slice(),this._final[12]=t[0],this._final[13]=t[1],void 0!==t[2]&&(this._final[14]=t[2]),this},i.prototype.setScale=function(t,s,e){return this.scale.set(t,s,e),this._final=this._final.slice(),this._final[0]=t[0],this._final[5]=t[1],void 0!==t[2]&&(this._final[10]=t[2]),this},i.prototype.setRotate=function(t,s,e){return this.rotate.set(t,s,e),this._final=a.call(this),this._final=l.build({translate:this.translate.get(),rotate:t,scale:this.scale.get(),skew:this.skew.get()}),this},i.prototype.setSkew=function(t,s,e){return this.skew.set(t,s,e),this._final=l.build({translate:this.translate.get(),rotate:this.rotate.get(),scale:this.scale.get(),skew:t}),this},i.prototype.set=function(t,s,e){this._final=t;var i=l.interpret(t),a=e?r.after(4,e):null;return this.translate.set(i.translate,s,a),this.rotate.set(i.rotate,s,a),this.skew.set(i.skew,s,a),this.scale.set(i.scale,s,a),this},i.prototype.setDefaultTransition=function(t){this.translate.setDefault(t),this.rotate.setDefault(t),this.skew.setDefault(t),this.scale.setDefault(t)},i.prototype.get=function(){return this.isActive()?a.call(this):this._final},i.prototype.getFinal=function(){return this._final},i.prototype.isActive=function(){return this.translate.isActive()||this.rotate.isActive()||this.scale.isActive()||this.skew.isActive()},i.prototype.halt=function(){this._final=this.get(),this.translate.halt(),this.rotate.halt(),this.skew.halt(),this.scale.halt()},e.exports=i});