/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * Owner: david@famo.us
 * @license MPL 2.0
 * @copyright Famous Industries, Inc. 2014
 */

define(["require","exports","module","./MultipleTransition","./TweenTransition"],function(t,e,i){function n(t){this.currentAction=null,this.actionQueue=[],this.callbackQueue=[],this.state=0,this.velocity=void 0,this._callback=void 0,this._engineInstance=null,this._currentMethod=null,this.set(t)}function s(){if(this._callback){var t=this._callback;this._callback=void 0,t()}if(this.actionQueue.length<=0)return void this.set(this.get());this.currentAction=this.actionQueue.shift(),this._callback=this.callbackQueue.shift();var e=null,i=this.currentAction[0],n=this.currentAction[1];n instanceof Object&&n.method?"string"==typeof(e=n.method)&&(e=o[e]):e=h,this._currentMethod!==e&&(!(i instanceof Object)||!0===e.SUPPORTS_MULTIPLE||i.length<=e.SUPPORTS_MULTIPLE?this._engineInstance=new e:this._engineInstance=new c(e),this._currentMethod=e),this._engineInstance.reset(this.state,this.velocity),void 0!==this.velocity&&(n.velocity=this.velocity),this._engineInstance.set(i,n,s.bind(this))}var c=t("./MultipleTransition"),h=t("./TweenTransition"),o={};n.registerMethod=function(t,e){return!(t in o)&&(o[t]=e,!0)},n.unregisterMethod=function(t){return t in o&&(delete o[t],!0)},n.prototype.set=function(t,e,i){if(!e)return this.reset(t),i&&i(),this;var n=[t,e];return this.actionQueue.push(n),this.callbackQueue.push(i),this.currentAction||s.call(this),this},n.prototype.reset=function(t,e){this._currentMethod=null,this._engineInstance=null,this._callback=void 0,this.state=t,this.velocity=e,this.currentAction=null,this.actionQueue=[],this.callbackQueue=[]},n.prototype.delay=function(t,e){this.set(this.get(),{duration:t,curve:function(){return 0}},e)},n.prototype.get=function(t){return this._engineInstance&&(this._engineInstance.getVelocity&&(this.velocity=this._engineInstance.getVelocity()),this.state=this._engineInstance.get(t)),this.state},n.prototype.isActive=function(){return!!this.currentAction},n.prototype.halt=function(){return this.set(this.get())},i.exports=n});