/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * Owner: mark@famo.us
 * @license MPL 2.0
 * @copyright Famous Industries, Inc. 2014
 */

define(["require","exports","module","famous/core/EventHandler","famous/core/Engine"],function(i,t,e){function s(i){this.options=Object.create(s.DEFAULT_OPTIONS),i&&this.setOptions(i),this._payload={delta:null,position:null,velocity:null,slip:!0},this._eventInput=new p,this._eventOutput=new p,p.setInputHandler(this,this._eventInput),p.setOutputHandler(this,this._eventOutput),this._position=void 0===this.options.direction?[0,0]:0,this._prevTime=void 0,this._prevVel=void 0,this._eventInput.on("mousewheel",n.bind(this)),this._eventInput.on("wheel",n.bind(this)),this._inProgress=!1,this._loopBound=!1}function o(){if(this._inProgress&&a()-this._prevTime>this.options.stallTime){this._inProgress=!1;var i=Math.abs(this._prevVel)>=this.options.minimumEndSpeed?this._prevVel:0,t=this._payload;t.position=this._position,t.velocity=i,t.slip=!0,this._eventOutput.emit("end",t)}}function n(i){i.preventDefault(),this._inProgress||(this._inProgress=!0,this._position=void 0===this.options.direction?[0,0]:0,c=this._payload,c.slip=!0,c.position=this._position,c.clientX=i.clientX,c.clientY=i.clientY,c.offsetX=i.offsetX,c.offsetY=i.offsetY,this._eventOutput.emit("start",c),this._loopBound||(h.on("prerender",o.bind(this)),this._loopBound=!0));var t=a(),e=this._prevTime||t,n=void 0!==i.wheelDeltaX?i.wheelDeltaX:-i.deltaX,p=void 0!==i.wheelDeltaY?i.wheelDeltaY:-i.deltaY;1===i.deltaMode&&(n*=this.options.lineHeight,p*=this.options.lineHeight),this.options.rails&&(Math.abs(n)>Math.abs(p)?p=0:n=0);var r,d,u=Math.max(t-e,l),_=n/u,v=p/u,m=this.options.scale;this.options.direction===s.DIRECTION_X?(d=m*n,r=m*_,this._position+=d):this.options.direction===s.DIRECTION_Y?(d=m*p,r=m*v,this._position+=d):(d=[m*n,m*p],r=[m*_,m*v],this._position[0]+=d[0],this._position[1]+=d[1]);var c=this._payload;c.delta=d,c.velocity=r,c.position=this._position,c.slip=!0,this._eventOutput.emit("update",c),this._prevTime=t,this._prevVel=r}var p=i("famous/core/EventHandler"),h=i("famous/core/Engine");s.DEFAULT_OPTIONS={direction:void 0,minimumEndSpeed:1/0,rails:!1,scale:1,stallTime:50,lineHeight:40},s.DIRECTION_X=0,s.DIRECTION_Y=1;var l=8,a=Date.now;s.prototype.getOptions=function(){return this.options},s.prototype.setOptions=function(i){void 0!==i.direction&&(this.options.direction=i.direction),void 0!==i.minimumEndSpeed&&(this.options.minimumEndSpeed=i.minimumEndSpeed),void 0!==i.rails&&(this.options.rails=i.rails),void 0!==i.scale&&(this.options.scale=i.scale),void 0!==i.stallTime&&(this.options.stallTime=i.stallTime)},e.exports=s});