/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * Owner: mark@famo.us
 * @license MPL 2.0
 * @copyright Famous Industries, Inc. 2014
 */

define(["require","exports","module","./TouchTracker","famous/core/EventHandler"],function(t,i,o){function n(t){this.options=Object.create(n.DEFAULT_OPTIONS),t&&this.setOptions(t),this._eventOutput=new h,this._touchTracker=new a,h.setOutputHandler(this,this._eventOutput),h.setInputHandler(this,this._touchTracker),this._touchTracker.on("trackstart",s.bind(this)),this._touchTracker.on("trackmove",e.bind(this)),this._touchTracker.on("trackend",c.bind(this)),this._payload={delta:null,position:null,velocity:null,clientX:void 0,clientY:void 0,count:0,touch:void 0},this._position=null}function s(t){var i,o;void 0!==this.options.direction?(this._position=0,i=0,o=0):(this._position=[0,0],i=[0,0],o=[0,0]);var n=this._payload;n.delta=o,n.position=this._position,n.velocity=i,n.clientX=t.x,n.clientY=t.y,n.count=t.count,n.touch=t.identifier,this._eventOutput.emit("start",n)}function e(t){var i=t.history,o=i[i.length-1],s=i[i.length-2],e=s.timestamp,c=o.timestamp,a=o.x-s.x,h=o.y-s.y;this.options.rails&&(Math.abs(a)>Math.abs(h)?h=0:a=0);var u,p,l=Math.max(c-e,r),d=a/l,_=h/l,v=this.options.scale;this.options.direction===n.DIRECTION_X?(p=v*a,u=v*d,this._position+=p):this.options.direction===n.DIRECTION_Y?(p=v*h,u=v*_,this._position+=p):(p=[v*a,v*h],u=[v*d,v*_],this._position[0]+=p[0],this._position[1]+=p[1]);var O=this._payload;O.delta=p,O.velocity=u,O.position=this._position,O.clientX=t.x,O.clientY=t.y,O.count=t.count,O.touch=t.identifier,this._eventOutput.emit("update",O)}function c(t){this._payload.count=t.count,this._eventOutput.emit("end",this._payload)}var a=t("./TouchTracker"),h=t("famous/core/EventHandler");n.DEFAULT_OPTIONS={direction:void 0,rails:!1,scale:1},n.DIRECTION_X=0,n.DIRECTION_Y=1;var r=8;n.prototype.setOptions=function(t){void 0!==t.direction&&(this.options.direction=t.direction),void 0!==t.rails&&(this.options.rails=t.rails),void 0!==t.scale&&(this.options.scale=t.scale)},n.prototype.getOptions=function(){return this.options},o.exports=n});