/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * Owner: mark@famo.us
 * @license MPL 2.0
 * @copyright Famous Industries, Inc. 2014
 */

define(["require","exports","module","famous/core/EventHandler"],function(t,e,h){function i(){this._eventInput=new n,this._eventOutput=new n,n.setInputHandler(this,this._eventInput),n.setOutputHandler(this,this._eventOutput),this.touchAEnabled=!1,this.touchAId=0,this.posA=null,this.timestampA=0,this.touchBEnabled=!1,this.touchBId=0,this.posB=null,this.timestampB=0,this._eventInput.on("touchstart",this.handleStart.bind(this)),this._eventInput.on("touchmove",this.handleMove.bind(this)),this._eventInput.on("touchend",this.handleEnd.bind(this)),this._eventInput.on("touchcancel",this.handleEnd.bind(this))}var n=t("famous/core/EventHandler");i.calculateAngle=function(t,e){var h=e[0]-t[0],i=e[1]-t[1];return Math.atan2(i,h)},i.calculateDistance=function(t,e){var h=e[0]-t[0],i=e[1]-t[1];return Math.sqrt(h*h+i*i)},i.calculateCenter=function(t,e){return[(t[0]+e[0])/2,(t[1]+e[1])/2]};var s=Date.now;i.prototype.handleStart=function(t){for(var e=0;e<t.changedTouches.length;e++){var h=t.changedTouches[e];this.touchAEnabled?this.touchBEnabled||(this.touchBId=h.identifier,this.touchBEnabled=!0,this.posB=[h.pageX,h.pageY],this.timestampB=s(),this._startUpdate(t)):(this.touchAId=h.identifier,this.touchAEnabled=!0,this.posA=[h.pageX,h.pageY],this.timestampA=s())}},i.prototype.handleMove=function(t){if(this.touchAEnabled&&this.touchBEnabled){for(var e,h=this.timestampA,i=this.timestampB,n=0;n<t.changedTouches.length;n++){var a=t.changedTouches[n];a.identifier===this.touchAId?(this.posA=[a.pageX,a.pageY],this.timestampA=s(),e=this.timestampA-h):a.identifier===this.touchBId&&(this.posB=[a.pageX,a.pageY],this.timestampB=s(),e=this.timestampB-i)}e&&this._moveUpdate(e)}},i.prototype.handleEnd=function(t){for(var e=0;e<t.changedTouches.length;e++){var h=t.changedTouches[e];h.identifier!==this.touchAId&&h.identifier!==this.touchBId||(this.touchAEnabled&&this.touchBEnabled&&this._eventOutput.emit("end",{touches:[this.touchAId,this.touchBId],angle:this._angle}),this.touchAEnabled=!1,this.touchAId=0,this.touchBEnabled=!1,this.touchBId=0)}},h.exports=i});