/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * Owner: david@famo.us
 * @license MPL 2.0
 * @copyright Famous Industries, Inc. 2014
 */

define(["require","exports","module","./Matrix"],function(t,i,r){function s(t,i,r,s){return 1===arguments.length?this.set(t):(this.w=void 0!==t?t:1,this.x=void 0!==i?i:0,this.y=void 0!==r?r:0,this.z=void 0!==s?s:0),this}var n=t("./Matrix"),o=new s(1,0,0,0);s.prototype.add=function(t){return o.setWXYZ(this.w+t.w,this.x+t.x,this.y+t.y,this.z+t.z)},s.prototype.sub=function(t){return o.setWXYZ(this.w-t.w,this.x-t.x,this.y-t.y,this.z-t.z)},s.prototype.scalarDivide=function(t){return this.scalarMultiply(1/t)},s.prototype.scalarMultiply=function(t){return o.setWXYZ(this.w*t,this.x*t,this.y*t,this.z*t)},s.prototype.multiply=function(t){var i=this.x,r=this.y,s=this.z,n=this.w,e=t.x,h=t.y,u=t.z,p=t.w||0;return o.setWXYZ(n*p-i*e-r*h-s*u,i*p+e*n+h*s-r*u,r*p+h*n+i*u-e*s,s*p+u*n+e*r-i*h)};var e=new s(1,0,0,0);s.prototype.rotateVector=function(t){return e.set(this.conj()),o.set(this.multiply(t).multiply(e))},s.prototype.inverse=function(){return o.set(this.conj().scalarDivide(this.normSquared()))},s.prototype.negate=function(){return this.scalarMultiply(-1)},s.prototype.conj=function(){return o.setWXYZ(this.w,-this.x,-this.y,-this.z)},s.prototype.normalize=function(t){return t=void 0===t?1:t,this.scalarDivide(t*this.norm())},s.prototype.makeFromAngleAndAxis=function(t,i){var r=i.normalize(),s=.5*t,n=-Math.sin(s);return this.x=n*r.x,this.y=n*r.y,this.z=n*r.z,this.w=Math.cos(s),this},s.prototype.setWXYZ=function(t,i,r,s){return o.clear(),this.w=t,this.x=i,this.y=r,this.z=s,this},s.prototype.set=function(t){return t instanceof Array?(this.w=0,this.x=t[0],this.y=t[1],this.z=t[2]):(this.w=t.w,this.x=t.x,this.y=t.y,this.z=t.z),this!==o&&o.clear(),this},s.prototype.put=function(t){t.set(o)},s.prototype.clone=function(){return new s(this)},s.prototype.clear=function(){return this.w=1,this.x=0,this.y=0,this.z=0,this},s.prototype.isEqual=function(t){return t.w===this.w&&t.x===this.x&&t.y===this.y&&t.z===this.z},s.prototype.dot=function(t){return this.w*t.w+this.x*t.x+this.y*t.y+this.z*t.z},s.prototype.normSquared=function(){return this.dot(this)},s.prototype.norm=function(){return Math.sqrt(this.normSquared())},s.prototype.isZero=function(){return!(this.x||this.y||this.z)},s.prototype.getTransform=function(){var t=this.normalize(1),i=t.x,r=t.y,s=t.z,n=t.w;return[1-2*r*r-2*s*s,2*i*r-2*s*n,2*i*s+2*r*n,0,2*i*r+2*s*n,1-2*i*i-2*s*s,2*r*s-2*i*n,0,2*i*s-2*r*n,2*r*s+2*i*n,1-2*i*i-2*r*r,0,0,0,0,1]};var h=new n;s.prototype.getMatrix=function(){var t=this.normalize(1),i=t.x,r=t.y,s=t.z,n=t.w;return h.set([[1-2*r*r-2*s*s,2*i*r+2*s*n,2*i*s-2*r*n],[2*i*r-2*s*n,1-2*i*i-2*s*s,2*r*s+2*i*n],[2*i*s+2*r*n,2*r*s-2*i*n,1-2*i*i-2*r*r]])};s.prototype.slerp=function(t,i){var r,s,n,e,h;return s=this.dot(t),1-s>1e-5?(r=Math.acos(s),n=Math.sin(r),e=Math.sin((1-i)*r)/n,h=Math.sin(i*r)/n):(e=1-i,h=i),o.set(this.scalarMultiply(e/h).add(t).multiply(h))},r.exports=s});