/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * Owner: mike@famo.us
 * @license MPL 2.0
 * @copyright Famous Industries, Inc. 2014
 */

define(["require","exports","module","famous/core/Entity","famous/core/Transform","famous/core/OptionsManager","famous/core/EventHandler","famous/transitions/Transitionable"],function(t,i,s){function e(t){this.options=Object.create(e.DEFAULT_OPTIONS),this.optionsManager=new a(this.options),t&&this.setOptions(t),this.id=n.register(this),this._ratios=new c(this.options.ratios),this._nodes=[],this._cachedDirection=null,this._cachedTotalLength=!1,this._cachedLengths=[],this._cachedTransforms=null,this._ratiosDirty=!1,this._eventOutput=new h,h.setOutputHandler(this,this._eventOutput)}function o(t,i,s){var o,n,a,h,c=0,_=i,d=0;for(this._cachedLengths=[],this._cachedTransforms=[],h=0;h<t.length;h++)n=t[h],a=this._nodes[h],"number"!=typeof n?_-=a.getSize()[s]||0:d+=n;for(h=0;h<t.length;h++)a=this._nodes[h],n=t[h],i="number"==typeof n?_*n/d:a.getSize()[s],o=s===e.DIRECTION_X?r.translate(c,0,0):r.translate(0,c,0),this._cachedTransforms.push(o),this._cachedLengths.push(i),c+=i}var n=t("famous/core/Entity"),r=t("famous/core/Transform"),a=t("famous/core/OptionsManager"),h=t("famous/core/EventHandler"),c=t("famous/transitions/Transitionable");e.DIRECTION_X=0,e.DIRECTION_Y=1,e.DEFAULT_OPTIONS={direction:e.DIRECTION_X,transition:!1,ratios:[]},e.prototype.render=function(){return this.id},e.prototype.setOptions=function(t){this.optionsManager.setOptions(t)},e.prototype.sequenceFrom=function(t){if(this._nodes=t,0===this._ratios.get().length){for(var i=[],s=0;s<this._nodes.length;s++)i.push(1);this.setRatios(i)}},e.prototype.setRatios=function(t,i,s){void 0===i&&(i=this.options.transition);var e=this._ratios;0===e.get().length&&(i=void 0),e.isActive()&&e.halt(),e.set(t,i,s),this._ratiosDirty=!0},e.prototype.commit=function(t){var i,s=t.size,e=t.transform,n=t.origin,a=t.opacity,h=this._ratios.get(),c=this.options.direction,_=s[c];(_!==this._cachedTotalLength||this._ratiosDirty||this._ratios.isActive()||c!==this._cachedDirection)&&(o.call(this,h,_,c),_!==this._cachedTotalLength&&(this._cachedTotalLength=_),c!==this._cachedDirection&&(this._cachedDirection=c),this._ratiosDirty&&(this._ratiosDirty=!1));for(var d=[],u=0;u<h.length;u++)i=[void 0,void 0],_=this._cachedLengths[u],i[c]=_,d.push({transform:this._cachedTransforms[u],size:i,target:this._nodes[u].render()});return s&&0!==n[0]&&0!==n[1]&&(e=r.moveThen([-s[0]*n[0],-s[1]*n[1],0],e)),{transform:e,size:s,opacity:a,target:d}},s.exports=e});