/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * Owner: felix@famo.us
 * @license MPL 2.0
 * @copyright Famous Industries, Inc. 2014
 */

define(["require","exports","module","famous/core/Entity","famous/core/RenderNode","famous/core/Transform","famous/core/ViewSequence","famous/core/EventHandler","famous/core/Modifier","famous/core/OptionsManager","famous/transitions/Transitionable","famous/transitions/TransitionableTransform"],function(t,i,s){function e(t){this.options=Object.create(e.DEFAULT_OPTIONS),this.optionsManager=new m(this.options),t&&this.setOptions(t),this.id=a.register(this),this._modifiers=[],this._states=[],this._contextSizeCache=[0,0],this._dimensionsCache=[0,0],this._activeCount=0,this._eventOutput=new u,u.setOutputHandler(this,this._eventOutput)}function o(t,i,s){var e=[t[0],t[1]];e[0]-=this.options.gutterSize[0]*(i-1),e[1]-=this.options.gutterSize[1]*(s-1);for(var o,a=Math.round(e[1]/s),h=Math.round(e[0]/i),c=0,u=0,f=0;f<s;f++){o=0;for(var m=0;m<i;m++)void 0===this._modifiers[u]?n.call(this,u,[h,a],[o,c,0],1):r.call(this,u,[h,a],[o,c,0],1),u++,o+=h+this.options.gutterSize[0];c+=a+this.options.gutterSize[1]}for(this._dimensionsCache=[this.options.dimensions[0],this.options.dimensions[1]],this._contextSizeCache=[t[0],t[1]],this._activeCount=s*i,f=this._activeCount;f<this._modifiers.length;f++)r.call(this,f,[Math.round(h),Math.round(a)],[0,0],0);this._eventOutput.emit("reflow")}function n(t,i,s,e){var o={transform:new d(h.translate.apply(null,s)),opacity:new p(e),size:new p(i)},n=new f({transform:o.transform,opacity:o.opacity,size:o.size});this._states[t]=o,this._modifiers[t]=n}function r(t,i,s,e){var o=this._states[t],n=o.size,r=o.opacity,a=o.transform,h=this.options.transition;a.halt(),r.halt(),n.halt(),a.setTranslate(s,h),n.set(i,h),r.set(e,h)}var a=t("famous/core/Entity"),h=(t("famous/core/RenderNode"),t("famous/core/Transform")),c=t("famous/core/ViewSequence"),u=t("famous/core/EventHandler"),f=t("famous/core/Modifier"),m=t("famous/core/OptionsManager"),p=t("famous/transitions/Transitionable"),d=t("famous/transitions/TransitionableTransform");e.DEFAULT_OPTIONS={dimensions:[1,1],transition:!1,gutterSize:[0,0]},e.prototype.render=function(){return this.id},e.prototype.setOptions=function(t){return this.optionsManager.setOptions(t)},e.prototype.sequenceFrom=function(t){t instanceof Array&&(t=new c(t)),this.sequence=t},e.prototype.commit=function(t){var i=t.transform,s=t.opacity,e=t.origin,n=t.size,r=this.options.dimensions[0],a=this.options.dimensions[1];n[0]===this._contextSizeCache[0]&&n[1]===this._contextSizeCache[1]&&r===this._dimensionsCache[0]&&a===this._dimensionsCache[1]||o.call(this,n,r,a);for(var c=this.sequence,u=[],f=0;c&&f<this._modifiers.length;){var m=c.get(),p=this._modifiers[f];f>=this._activeCount&&this._states[f].opacity.isActive()&&(this._modifiers.splice(f,1),this._states.splice(f,1)),m&&u.push(p.modify({origin:e,target:m.render()})),c=c.getNext(),f++}return n&&(i=h.moveThen([-n[0]*e[0],-n[1]*e[1],0],i)),{transform:i,opacity:s,size:n,target:u}},s.exports=e});