/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * Owner: david@famo.us
 * @license MPL 2.0
 * @copyright Famous Industries, Inc. 2014
 */

define(["require","exports","module","./Force","famous/math/Vector"],function(t,o,n){function i(t){this.options=Object.create(this.constructor.DEFAULT_OPTIONS),t&&this.setOptions(t),this.disp=new p(0,0,0),c.call(this),h.call(this)}function s(t){this.forceFunction=t}function r(){var t=this.options;t.stiffness=Math.pow(2*u/t.period,2)}function e(){var t=this.options;t.damping=4*u*t.dampingRatio/t.period}function a(t,o){return.5*t*o*o}function c(){s.call(this,this.options.forceFunction),r.call(this),e.call(this)}var h=t("./Force"),p=t("famous/math/Vector");i.prototype=Object.create(h.prototype),i.prototype.constructor=i;var u=Math.PI;i.FORCE_FUNCTIONS={FENE:function(t,o){var n=.99*o,i=Math.max(Math.min(t,n),-n);return i/(1-i*i/(o*o))},HOOK:function(t){return t}},i.DEFAULT_OPTIONS={period:300,dampingRatio:.1,length:0,maxLength:1/0,anchor:void 0,forceFunction:i.FORCE_FUNCTIONS.HOOK},i.prototype.setOptions=function(t){void 0!==t.anchor&&(t.anchor.position instanceof p&&(this.options.anchor=t.anchor.position),t.anchor instanceof p&&(this.options.anchor=t.anchor),t.anchor instanceof Array&&(this.options.anchor=new p(t.anchor))),void 0!==t.period&&(this.options.period=t.period),void 0!==t.dampingRatio&&(this.options.dampingRatio=t.dampingRatio),void 0!==t.length&&(this.options.length=t.length),void 0!==t.forceFunction&&(this.options.forceFunction=t.forceFunction),void 0!==t.maxLength&&(this.options.maxLength=t.maxLength),c.call(this)},i.prototype.applyForce=function(t,o){for(var n=this.force,i=this.disp,s=this.options,r=s.stiffness,e=s.damping,c=s.length,h=s.maxLength,p=s.anchor||o.position,u=0;u<t.length;u++){var f=t[u],l=f.position,d=f.velocity;p.sub(l).put(i);var m=i.norm()-c;if(0===m)return;var g=f.mass;r*=g,e*=g,i.normalize(r*this.forceFunction(m,h)).put(n),e&&(o?n.add(d.sub(o.velocity).mult(-e)).put(n):n.add(d.mult(-e)).put(n)),f.applyForce(n),o&&o.applyForce(n.mult(-1)),this.setEnergy(a(r,m))}},i.prototype.getEnergy=function(t){var o=this.options,n=o.length,i=o.anchor,s=o.stiffness,r=i.sub(t.position).norm()-n;return.5*s*r*r},i.prototype.setAnchor=function(t){this.options.anchor||(this.options.anchor=new p),this.options.anchor.set(t)},n.exports=i});