/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * Owner: mark@famo.us
 * @license MPL 2.0
 * @copyright Famous Industries, Inc. 2014
 */

define(["require","exports","module","./EventEmitter"],function(t,e,i){function n(){r.apply(this,arguments),this.downstream=[],this.downstreamFn=[],this.upstream=[],this.upstreamListeners={}}var r=t("./EventEmitter");n.prototype=Object.create(r.prototype),n.prototype.constructor=n,n.setInputHandler=function(t,e){t.trigger=e.trigger.bind(e),e.subscribe&&e.unsubscribe&&(t.subscribe=e.subscribe.bind(e),t.unsubscribe=e.unsubscribe.bind(e))},n.setOutputHandler=function(t,e){e instanceof n&&e.bindThis(t),t.pipe=e.pipe.bind(e),t.unpipe=e.unpipe.bind(e),t.on=e.on.bind(e),t.addListener=t.on,t.removeListener=e.removeListener.bind(e)},n.prototype.emit=function(t,e){r.prototype.emit.apply(this,arguments);var i=0;for(i=0;i<this.downstream.length;i++)this.downstream[i].trigger&&this.downstream[i].trigger(t,e);for(i=0;i<this.downstreamFn.length;i++)this.downstreamFn[i](t,e);return this},n.prototype.trigger=n.prototype.emit,n.prototype.pipe=function(t){if(t.subscribe instanceof Function)return t.subscribe(this);var e=t instanceof Function?this.downstreamFn:this.downstream;return e.indexOf(t)<0&&e.push(t),t instanceof Function?t("pipe",null):t.trigger&&t.trigger("pipe",null),t},n.prototype.unpipe=function(t){if(t.unsubscribe instanceof Function)return t.unsubscribe(this);var e=t instanceof Function?this.downstreamFn:this.downstream,i=e.indexOf(t);return i>=0&&(e.splice(i,1),t instanceof Function?t("unpipe",null):t.trigger&&t.trigger("unpipe",null),t)},n.prototype.on=function(t,e){if(r.prototype.on.apply(this,arguments),!(t in this.upstreamListeners)){var i=this.trigger.bind(this,t);this.upstreamListeners[t]=i;for(var n=0;n<this.upstream.length;n++)this.upstream[n].on(t,i)}return this},n.prototype.addListener=n.prototype.on,n.prototype.subscribe=function(t){if(this.upstream.indexOf(t)<0){this.upstream.push(t);for(var e in this.upstreamListeners)t.on(e,this.upstreamListeners[e])}return this},n.prototype.unsubscribe=function(t){var e=this.upstream.indexOf(t);if(e>=0){this.upstream.splice(e,1);for(var i in this.upstreamListeners)t.removeListener(i,this.upstreamListeners[i])}return this},i.exports=n});