/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * Owner: mark@famo.us
 * @license MPL 2.0
 * @copyright Famous Industries, Inc. 2014
 */

define(["require","exports","module","famous/core/Scene","famous/core/Surface","famous/core/Transform","famous/core/View"],function(s,t,e){function o(s){c.apply(this,arguments),this.title=new n({classes:this.options.classes,content:this.options.content}),this.back=new n({size:[this.options.size[1],this.options.size[1]],classes:this.options.classes,content:this.options.backContent}),this.back.on("click",function(){this._eventOutput.emit("back",{})}.bind(this)),this.more=new n({size:[this.options.size[1],this.options.size[1]],classes:this.options.classes,content:this.options.moreContent}),this.more.on("click",function(){this._eventOutput.emit("more",{})}.bind(this)),this.layout=new i({id:"master",size:this.options.size,target:[{transform:a.inFront,origin:[0,.5],target:this.back},{origin:[.5,.5],target:this.title},{transform:a.inFront,origin:[1,.5],target:this.more}]}),this._add(this.layout),this._optionsManager.on("change",function(s){var t=s.id,e=s.value;"size"===t?(this.layout.id.master.setSize(e),this.title.setSize(e),this.back.setSize([e[1],e[1]]),this.more.setSize([e[1],e[1]])):"backClasses"===t?this.back.setOptions({classes:this.options.classes.concat(this.options.backClasses)}):"backContent"===t?this.back.setContent(this.options.backContent):"classes"===t?(this.title.setOptions({classes:this.options.classes}),this.back.setOptions({classes:this.options.classes.concat(this.options.backClasses)}),this.more.setOptions({classes:this.options.classes.concat(this.options.moreClasses)})):"content"===t?this.setContent(this.options.content):"moreClasses"===t?this.more.setOptions({classes:this.options.classes.concat(this.options.moreClasses)}):"moreContent"===t&&this.more.setContent(this.options.content)}.bind(this))}var i=s("famous/core/Scene"),n=s("famous/core/Surface"),a=s("famous/core/Transform"),c=s("famous/core/View");o.prototype=Object.create(c.prototype),o.prototype.constructor=o,o.DEFAULT_OPTIONS={size:[void 0,50],backClasses:["back"],backContent:"&#x25c0;",classes:["navigation"],content:"",moreClasses:["more"],moreContent:"&#x271a;"},o.prototype.setContent=function(s){return this.title.setContent(s)},e.exports=o});