/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * Owner: david@famo.us
 * @license MPL 2.0
 * @copyright Famous Industries, Inc. 2014
 */

define(["require","exports","module","./Constraint","./Wall","famous/math/Vector"],function(t,o,i){function n(t){this.options=Object.create(n.DEFAULT_OPTIONS),t&&this.setOptions(t),e.call(this,t.sides||this.options.sides),a.call(this)}function s(t,o,i){var s,e=n.SIDES;switch(parseInt(t)){case e.LEFT:s=o[0]*i[0];break;case e.TOP:s=o[1]*i[1];break;case e.FRONT:s=o[2]*i[2];break;case e.RIGHT:s=o[0]*(1-i[0]);break;case e.BOTTOM:s=o[1]*(1-i[1]);break;case e.BACK:s=o[2]*(1-i[2])}return s}function e(t){this.components={};for(var o=this.components,i=0;i<t.length;i++){var n=t[i];o[i]=new c({normal:h[n].clone(),distance:s(n,this.options.size,this.options.origin)})}}function r(t){this.forEach(function(o){o.setOptions(t)});for(var o in t)this.options[o]=t[o]}var a=t("./Constraint"),c=t("./Wall"),p=t("famous/math/Vector");n.prototype=Object.create(a.prototype),n.prototype.constructor=n,n.ON_CONTACT=c.ON_CONTACT,n.SIDES={LEFT:0,RIGHT:1,TOP:2,BOTTOM:3,FRONT:4,BACK:5,TWO_DIMENSIONAL:[0,1,2,3],THREE_DIMENSIONAL:[0,1,2,3,4,5]},n.DEFAULT_OPTIONS={sides:n.SIDES.TWO_DIMENSIONAL,size:[window.innerWidth,window.innerHeight,0],origin:[.5,.5,.5],drift:.5,slop:0,restitution:.5,onContact:n.ON_CONTACT.REFLECT};var h={0:new p(1,0,0),1:new p(-1,0,0),2:new p(0,1,0),3:new p(0,-1,0),4:new p(0,0,1),5:new p(0,0,-1)};n.prototype.setOptions=function(t){var o=!1;void 0!==t.restitution&&r.call(this,{restitution:t.restitution}),void 0!==t.drift&&r.call(this,{drift:t.drift}),void 0!==t.slop&&r.call(this,{slop:t.slop}),void 0!==t.onContact&&r.call(this,{onContact:t.onContact}),void 0!==t.size&&(o=!0),void 0!==t.sides&&(this.options.sides=t.sides),void 0!==t.origin&&(o=!0),o&&this.setSize(t.size,t.origin)},n.prototype.setSize=function(t,o){o=o||this.options.origin,o.length<3&&(o[2]=.5),this.forEach(function(i,n){var e=s(n,t,o);i.setOptions({distance:e})}),this.options.size=t,this.options.origin=o},n.prototype.applyConstraint=function(t,o,i){this.forEach(function(n){n.applyConstraint(t,o,i)})},n.prototype.forEach=function(t){var o=this.options.sides;for(var i in this.sides)t(o[i],i)},n.prototype.rotateZ=function(t){this.forEach(function(o){var i=o.options.normal;i.rotateZ(t).put(i)})},n.prototype.rotateX=function(t){this.forEach(function(o){var i=o.options.normal;i.rotateX(t).put(i)})},n.prototype.rotateY=function(t){this.forEach(function(o){var i=o.options.normal;i.rotateY(t).put(i)})},i.exports=n});