/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * Owner: david@famo.us
 * @license MPL 2.0
 * @copyright Famous Industries, Inc. 2014
 */

define(["require","exports","module","./Constraint","famous/math/Vector"],function(t,o,i){function n(t){this.options=Object.create(n.DEFAULT_OPTIONS),t&&this.setOptions(t),this.diff=new l,this.impulse=new l,p.call(this)}function s(t,o){return o.dot(t)}function e(t){var o=this.options.normal,i=this.options.distance;return t.dot(o)+i}function a(t,o,i){var s=t.position,e=t.velocity,a=t.mass,r=this.options.normal,p=this.options.onContact,l=this.options.restitution,c=this.impulse,u=this.options.drift,h=-this.options.slop;if(this._eventOutput){var d={particle:t,wall:this,overlap:o,normal:r};this._eventOutput.emit("preCollision",d),this._eventOutput.emit("collision",d)}switch(p){case n.ON_CONTACT.REFLECT:var m=o<h?-((1+l)*r.dot(e)+u/i*(o-h))/(a*i+0):-(1+l)*r.dot(e)/(a*i+0);c.set(r.mult(i*m)),t.applyImpulse(c),t.setPosition(s.add(r.mult(-o)))}this._eventOutput&&this._eventOutput.emit("postCollision",d)}function r(t,o,i){var s=this.options.onContact,e=t.position,a=this.options.normal;s===n.ON_CONTACT.REFLECT&&t.setPosition(e.add(a.mult(-o)))}var p=t("./Constraint"),l=t("famous/math/Vector");n.prototype=Object.create(p.prototype),n.prototype.constructor=n,n.ON_CONTACT={REFLECT:0,SILENT:1},n.DEFAULT_OPTIONS={restitution:.5,drift:.5,slop:0,normal:[1,0,0],distance:0,onContact:n.ON_CONTACT.REFLECT},n.prototype.setOptions=function(t){void 0!==t.normal&&(t.normal instanceof l&&(this.options.normal=t.normal.clone()),t.normal instanceof Array&&(this.options.normal=new l(t.normal))),void 0!==t.restitution&&(this.options.restitution=t.restitution),void 0!==t.drift&&(this.options.drift=t.drift),void 0!==t.slop&&(this.options.slop=t.slop),void 0!==t.distance&&(this.options.distance=t.distance),void 0!==t.onContact&&(this.options.onContact=t.onContact)},n.prototype.applyConstraint=function(t,o,i){for(var n=this.options.normal,p=0;p<t.length;p++){var l=t[p],c=l.position,u=l.velocity,h=l.radius||0,d=e.call(this,c.add(n.mult(-h))),m=s.call(this,n,u);d<=0&&(m<0?a.call(this,l,d,i):r.call(this,l,d,i))}},i.exports=n});